apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-d-s
  namespace : default
spec:
  selector:
    matchLabels:
      app: nginx-d-s
  template:
    metadata:
      labels:
        app: nginx-d-s
    spec:
      affinity:
       nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: env
              operator: In
              values:
              - dev
      containers:
      - name: nginx-d-s
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-d-s
  namespace: default
spec:
  selector:
    app: nginx-d-s
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31004
