apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    disktype: ssd
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-depoly
spec:
  selector:
    app: nginx-depoly
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
