apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depoly
spec:
  selector:
    matchLabels:
      app: nginx-depoly
  template:
    metadata:
      labels:
        app: nginx-depoly
    spec:
      containers:
      - name: nginx-depoly
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
  nodeSelector: 
     hardware: nginx-node
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-depoly
spec:
  selector:
    app: nginx-depoly
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
